package app.pojos;
// Generated May 25, 2022 9:50:17 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer UId;
     private String UName;
     private String UNickname;
     private String UPassword;
     private String URole;
     private byte[] UPic;

    public Users() {
    }

    public Users(String UName, String UNickname, String UPassword, String URole, byte[] UPic) {
       this.UName = UName;
       this.UNickname = UNickname;
       this.UPassword = UPassword;
       this.URole = URole;
       this.UPic = UPic;
    }
   
    public Integer getUId() {
        return this.UId;
    }
    
    public void setUId(Integer UId) {
        this.UId = UId;
    }
    public String getUName() {
        return this.UName;
    }
    
    public void setUName(String UName) {
        this.UName = UName;
    }
    public String getUNickname() {
        return this.UNickname;
    }
    
    public void setUNickname(String UNickname) {
        this.UNickname = UNickname;
    }
    public String getUPassword() {
        return this.UPassword;
    }
    
    public void setUPassword(String UPassword) {
        this.UPassword = UPassword;
    }
    public String getURole() {
        return this.URole;
    }
    
    public void setURole(String URole) {
        this.URole = URole;
    }
    public byte[] getUPic() {
        return this.UPic;
    }
    
    public void setUPic(byte[] UPic) {
        this.UPic = UPic;
    }




}


